---
apiVersion: batch/v1
kind: Job
metadata:
  name: tileserver-import
spec:
  template:
    spec:
      containers:
        - image: greenhalos/tile-server-import:latest
          name: tileserver-import
          imagePullPolicy: Always
      restartPolicy: Never
  backoffLimit: 4
